# config.yaml

planet:
  name: HAT-P-14b       # Planet name. 
  period:     4.62767     # fixed 
  duration:   0.0925       # prior
  t0:         59738.462267    # prior, needs to be estimated from whitelight glance
  b:          0.9        # prior
  rprs:      0.0805       # prior

stellar:
  feh:   0.13
  teff:  6700
  logg:  4.22
  ld_model: "stagger"
  ld_data_path: "../exotic_ld_data"

instrument: 'NIRISS/SOSS'
order: 1
nrs: # 2              # 1 or 2
path: '/scratch/midway3/tfairnington/'
input_dir: './' # where the calints files are stored relative to path
output_dir: 'HAT-P-14b_SOSS_FREELD_LINEAR' # where the output files are stored relative to path
fits_file: 'HAT-P-14_box_spectra_fullres.fits'
resolution:
  high: 'reference' # nm resolution to bin spectroscopic curves
  low:  100 # nm resolution to bin spectroscopic curves [optional: not triggered if not low-res]
  reference_grid: 'prism_template.csv'
  #reference_grid_lr: 'prism_template.csv'
flags:
  detrending_type: 'linear'
  interpolate_trend: False # Option to interpolate trend coefficients from low res to high res | defaults to False
  interpolate_ld: False # Option to interpolate LD coefficients from low res ot high res | defaults to false
  fix_ld: False
  need_lowres: True # Option to fit low res first if other flags are false to clip spectroscopic outliers, reccommended
  #mask_start: 60457.68
  #mask_end: 60457.698
outlier_clip:
  whitelight_sigma:   4 # sigma to clip outliers from whitelight residual 
  spectroscopic_sigma: 4 # sigma to clip outliers from spectroscopic residuals

host_device: "gpu"      # 'gpu' or "cpu" | reminder, if using gpu you need jax[cuda]<=0.4.31, cpu needs jax[cpu]<=0.4.31




