# config.yaml

planet:
  name: HATP18b       # Planet name. 
  period:     5.50802941     # fixed 
  duration:   0.1131       # prior
  t0:         60861.49    # prior, needs to be estimated from whitelight glance
  b:          0.148         # prior
  rprs:      0.1356       # prior

stellar:
  feh:   0.14
  teff:  4790
  logg:  4.588
  ld_model: "stagger"
  ld_data_path: "../exotic_ld_data"

instrument: 'MIRI/LRS'
order: None
nrs: None              # 1 or 2
path: 'spectra/HAT-P-18'
input_dir: 'MIRI' # where the calints files are stored relative to path
output_dir: 'CUT30_LRS_FREELD_EXPLINEAR' # where the output files are stored relative to path
fits_file: 'HAT-P-18b_box_spectra_fullres.fits'
#resolution:
#  high: 100 # nm resolution to bin spectroscopic curves
#  low:  10 # nm resolution to bin spectroscopic curves [optional: not triggered if not low-res]
pixels:
   high: 6
   low: 8
flags:
  detrending_type: 'explinear'
  interpolate_trend: False # Option to interpolate trend coefficients from low res to high res | defaults to False
  interpolate_ld: False # Option to interpolate LD coefficients from low res ot high res | defaults to false
  fix_ld: False
  need_lowres: True # Option to fit low res first if other flags are false to clip spectroscopic outliers, reccommended
  #mask_start: 59743.343
  #mask_end: 59743.365
outlier_clip:
  whitelight_sigma:   4 # sigma to clip outliers from whitelight residual 
  spectroscopic_sigma: 4 # sigma to clip outliers from spectroscopic residuals
  mask_integrations_start: 30
host_device: "gpu"      # 'gpu' or "cpu" | reminder, if using gpu you need jax[cuda]<=0.4.31, cpu needs jax[cpu]<=0.4.31




