# config.yaml

planet:
  name: TOI-270d       # needs to match directory where Stage 3 files are stored, i.e. 'TOI1130b_NIRSPEC'
  period:     [11.379573,3.3601538]      # fixed 
  duration:   [0.0895,0.05779]       # prior
  t0:         [60221.30,60221.25]   # prior, needs to be estimated from whitelight glance
  b:          [0.19,0.19]          # prior
  rprs:      [0.05163,0.02920]        # prior

stellar:
  feh:   -0.20
  teff:  3500
  logg:  4.87
  ld_model: "mps1"
  ld_data_path: "../exotic_ld_data"

instrument: 'NIRSPEC/G395H'
order: #1 
nrs: 1 #None              # 1 or 2
path: 'spectra/TOI-270'
input_dir: 'NIRSPEC' # where the calints files are stored relative to path
output_dir: 'V1_NRS1_FIXEDLD_LINEAR' # where the output files are stored relative to path
fits_file: 'TOI-270_visit1_nrs1_box_spectra_fullres.fits'
resolution:
  high: 'native' # nm resolution to bin spectroscopic curves
  low:  55 # nm resolution to bin spectroscopic curves [optional: not triggered if not low-res]

flags:
  detrending_type: 'linear'
  interpolate_trend: False # Option to interpolate trend coefficients from low res to high res | defaults to False
  interpolate_ld: False # Option to interpolate LD coefficients from low res ot high res | defaults to false
  fix_ld: True
  need_lowres: True # Option to fit low res first if other flags are false to clip spectroscopic outliers, reccommended

outlier_clip:
  whitelight_sigma:   4 # sigma to clip outliers from whitelight residual 
  spectroscopic_sigma: 4 # sigma to clip outliers from spectroscopic residuals

host_device: "gpu"      # 'gpu' or "cpu" | reminder, if using gpu you need jax[cuda]<=0.4.31, cpu needs jax[cpu]<=0.4.31




