# config.yaml

planet:
  name: TOI1130b       # needs to match directory where Stage 3 files are stored, i.e. 'TOI1130b_NIRSPEC'
  period:     4.074554     # fixed 
  duration:   0.0765       # prior
  t0:         60542.56     # prior, needs to be estimated from whitelight glance
  b:          0.51         # prior
  rprs:      0.0480       # prior

stellar:
  feh:   0.11
  teff:  4360
  logg:  4.55
  ld_model: "stagger"
  ld_data_path: "../exotic_ld_data"

instrument: 'NIRSPEC/G395H'
order: None 
nrs: 1              # 1 or 2
path: 'spectra/TOI-1130'
input_dir: 'NIRSPEC' # where the calints files are stored relative to path
output_dir: 'NRS1_FIXEDLD_LINEAR' # where the output files are stored relative to path
fits_file: 'TOI-1130_nrs1_box_spectra_fullres.fits'
resolution:
  high: 'native' # nm resolution to bin spectroscopic curves
  low:  50 # nm resolution to bin spectroscopic curves [optional: not triggered if not low-res]

flags:
  detrending_type: 'linear'
  interpolate_trend: False # Option to interpolate trend coefficients from low res to high res | defaults to False
  interpolate_ld: False # Option to interpolate LD coefficients from low res ot high res | defaults to false
  fix_ld: True
  need_lowres: True # Option to fit low res first if other flags are false to clip spectroscopic outliers, reccommended

outlier_clip:
  whitelight_sigma:   4 # sigma to clip outliers from whitelight residual 
  spectroscopic_sigma: 4 # sigma to clip outliers from spectroscopic residuals

host_device: "gpu"      # 'gpu' or "cpu" | reminder, if using gpu you need jax[cuda]<=0.4.31, cpu needs jax[cpu]<=0.4.31




