# config.yaml

planet:
  name: WASP-96b       # Planet name. 
  period:     3.42525674     # fixed 
  duration:   0.101       # prior
  t0:         60532.28    # prior, needs to be estimated from whitelight glance
  b:          0.724        # prior
  rprs:      0.11986       # prior

stellar:
  feh:   0.24
  teff:  5700
  logg:  4.40
  ld_model: "stagger"
  ld_data_path: "../exotic_ld_data"

instrument: 'NIRSPEC/G395H'
order: # 1
nrs:  1              # 1 or 2
path: '/scratch/midway3/tfairnington/'
input_dir: 'FITS' # where the calints files are stored relative to path
output_dir: 'WASP-96b_NRS1_FREELD_GP' # where the output files are stored relative to path
fits_file: 'WASP-96_nrs1_box_spectra_fullres_G395H.fits'
resolution:
  high: 'reference' # nm resolution to bin spectroscopic curves
  low:  40 # nm resolution to bin spectroscopic curves [optional: not triggered if not low-res]
  reference_grid: 'prism_template.csv'
  #reference_grid_lr: 'prism_template.csv'
flags:
  detrending_type: 'GP'
  interpolate_trend: False # Option to interpolate trend coefficients from low res to high res | defaults to False
  interpolate_ld: False # Option to interpolate LD coefficients from low res ot high res | defaults to false
  fix_ld: False
  need_lowres: True # Option to fit low res first if other flags are false to clip spectroscopic outliers, reccommended
  #mask_start: 60457.68
  #mask_end: 60457.698
  mask_integrations_start: 30
outlier_clip:
  whitelight_sigma:   4 # sigma to clip outliers from whitelight residual 
  spectroscopic_sigma: 4 # sigma to clip outliers from spectroscopic residuals

host_device: "gpu"      # 'gpu' or "cpu" | reminder, if using gpu you need jax[cuda]<=0.4.31, cpu needs jax[cpu]<=0.4.31




