planet:
  name: HAT-P-11
  period: 4.887802443
  duration: 0.0981875
  t0: 60504.975
  b: 0.209
  rprs: 0.0585
stellar:
  feh: 0.12
  teff: 4692
  logg: 3.99
  teff_sigma: 97
  logg_sigma: 0.3
  feh_sigma: 0.05
  ld_model: stagger
  ld_data_path: ../exotic_ld_data
  ld_prior_min_sigma: 0.0001
  ld_prior_cache_dir: /scratch/midway3/tfairnington/accel_parity/20260902a/HAT-P-11_G395H_NRS2_V2_STELLARINFORMEDLD_POWER2_LINEAR/shared_ld_prior_cache
instrument: NIRSPEC/G395H
order: null
nrs: 2
path: /scratch/midway3/tfairnington/
input_dir: FITS
output_dir: HAT-P-11_G395H_NRS2_V2_STELLARINFORMEDLD_POWER2_LINEAR_PARITY_20260902a_C
fits_file: HAT-P-11_nrs2_box_spectra_fullres_G395H_V2.fits
resolution:
  high: reference
  low: 20
  reference_grid: prism_template.csv
flags:
  vmap_chunk: 40
  detrending_type: linear
  interpolate_trend: false
  interpolate_ld: false
  ld_prior: stellarprior
  need_lowres: true
  ld_profile: power2
  mask_start: jnp.min(t)
  mask_end: jnp.min(t) + 0.007
  mask_integrations_start: None
  spectro_sampler: laplace_is
  spectro_jitter_prior: lognormal
  whitelight_num_warmup: 1000
  whitelight_num_samples: 1000
outlier_clip:
  whitelight_sigma: 5
  spectroscopic_sigma: 5
host_device: gpu
