planet:
  name: WASP-107
  period: 5.7214876
  duration: 0.11470000000000001
  t0: 60107.0
  b: 0.139
  rprs: 0.142988
stellar:
  feh: -0.02
  teff: 4488
  logg: 4.15
  teff_sigma: 227
  logg_sigma: 0.78
  feh_sigma: 0.13
  ld_model: stagger
  ld_data_path: ../exotic_ld_data
  ld_prior_min_sigma: 0.0001
  ld_prior_cache_dir: /scratch/midway3/tfairnington/accel_parity/20260902a/WASP-107_SOSS_ORDER1_STELLARINFORMEDLD_POWER2_SPOT/shared_ld_prior_cache
instrument: NIRISS/SOSS
order: 1
path: /scratch/midway3/tfairnington/
input_dir: FITS
output_dir: WASP-107_SOSS_ORDER1_STELLARINFORMEDLD_POWER2_SPOT_PARITY_20260902a_C
fits_file: WASP-107_box_spectra_fullres.fits
resolution:
  high: reference
  low: 20
  reference_grid: prism_template.csv
flags:
  vmap_chunk: 40
  detrending_type: spot
  interpolate_trend: false
  interpolate_ld: false
  ld_prior: stellarprior
  need_lowres: true
  ld_profile: power2
  spot_center: 60107.049
  spot_width: 0.005
  spot_amp: 0.001
  mask_start:
  - jnp.min(t)
  - 60107.0142
  mask_end:
  - jnp.min(t) + 0.007
  - 60107.0146
  mask_integrations_start: None
  spectro_sampler: laplace_is
  spectro_jitter_prior: lognormal
  whitelight_num_warmup: 1000
  whitelight_num_samples: 1000
outlier_clip:
  whitelight_sigma: 5
  spectroscopic_sigma: 5
host_device: gpu
