planet:
  name: WASP-166
  period: 5.4435423
  duration: 0.15
  t0: 60309.4
  b: 0.398
  rprs: 0.0515
stellar:
  feh: 0.25
  teff: 6142
  logg: 4.45
  teff_sigma: 22
  logg_sigma: 0.04
  feh_sigma: 0.02
  ld_model: stagger
  ld_data_path: ../exotic_ld_data
  ld_prior_min_sigma: 0.0001
  ld_prior_cache_dir: /scratch/midway3/tfairnington/accel_parity/20260902a/WASP-166_SOSS_ORDER1_STELLARINFORMEDLD_POWER2_LINEAR/shared_ld_prior_cache
instrument: NIRISS/SOSS
order: 1
path: /scratch/midway3/tfairnington/
input_dir: FITS
output_dir: WASP-166_SOSS_ORDER1_STELLARINFORMEDLD_POWER2_LINEAR_PARITY_20260902a_C
fits_file: WASP-166_box_spectra_fullres.fits
resolution:
  high: reference
  low: 20
  reference_grid: prism_template.csv
flags:
  vmap_chunk: 40
  detrending_type: linear
  interpolate_trend: false
  interpolate_ld: false
  ld_prior: stellarprior
  need_lowres: true
  ld_profile: power2
  mask_start:
  - 60309.18
  mask_end:
  - 60309.1924
  mask_integrations_start: None
  spectro_sampler: laplace_is
  spectro_jitter_prior: lognormal
  whitelight_num_warmup: 1000
  whitelight_num_samples: 1000
outlier_clip:
  whitelight_sigma: 5
  spectroscopic_sigma: 5
host_device: gpu
