planet:
  name: WASP-94
  period: 3.9502001
  duration: 0.189675
  t0: 60595.21518
  b: 0.15
  rprs: 0.107
  a_rs: 7.3
  ecc: 0.0
  omega: 0.0
stellar:
  feh: 0.37
  teff: 6217
  logg: 4.27
  teff_sigma: 19
  logg_sigma: 0.04
  feh_sigma: 0.01
  ld_model: stagger
  ld_data_path: ../exotic_ld_data
  ld_prior_min_sigma: 0.0001
  ld_prior_cache_dir: /scratch/midway3/tfairnington/accel_parity/20260902a/WASP-94_SOSS_ORDER1_STELLARINFORMEDLD_POWER2_LINEAR/shared_ld_prior_cache
instrument: NIRISS/SOSS
order: 1
path: /scratch/midway3/tfairnington/
input_dir: FITS
output_dir: WASP-94_SOSS_ORDER1_STELLARINFORMEDLD_POWER2_LINEAR_PARITY_20260902a_C
fits_file: WASP-94_box_spectra_fullres.fits
resolution:
  high: reference
  low: 20
  reference_grid: prism_template.csv
flags:
  vmap_chunk: 40
  detrending_type: linear
  interpolate_trend: false
  interpolate_ld: false
  ld_prior: stellarprior
  need_lowres: true
  ld_profile: power2
  mask_start: jnp.min(t)
  mask_end: jnp.min(t) + 0.0208
  spectro_sampler: laplace_is
  spectro_jitter_prior: lognormal
  whitelight_num_warmup: 1000
  whitelight_num_samples: 1000
outlier_clip:
  whitelight_sigma: 5
  spectroscopic_sigma: 5
host_device: gpu
