planet:
  name: HAT-P-30
  period: 2.8106007
  duration: 0.09374689166666667
  t0: 60765.195
  b: 0.86
  rprs: 0.1109
stellar:
  feh: 0.1
  teff: 6321
  logg: 4.45
  teff_sigma: 30
  logg_sigma: 0.04
  feh_sigma: 0.02
  ld_model: stagger
  ld_data_path: ../exotic_ld_data
  ld_prior_min_sigma: 0.0001
  ld_prior_cache_dir: /scratch/midway3/tfairnington/accel_parity/20260902d/HAT-P-30_SOSS_ORDER1_STELLARINFORMEDLD_POWER2_LINEAR/shared_ld_prior_cache
instrument: NIRISS/SOSS
order: 1
path: /scratch/midway3/tfairnington/
input_dir: FITS
output_dir: HAT-P-30_SOSS_ORDER1_STELLARINFORMEDLD_POWER2_LINEAR_PARITY_20260902d_D
fits_file: HAT-P-30_box_spectra_fullres.fits
resolution:
  high: reference
  low: 20
  reference_grid: prism_template.csv
flags:
  vmap_chunk: 40
  detrending_type: linear
  interpolate_trend: false
  interpolate_ld: false
  ld_prior: stellarprior
  need_lowres: true
  ld_profile: power2
  mask_start:
  - jnp.min(t)
  - 60765.1973
  mask_end:
  - jnp.min(t) + 0.007
  - 60765.1974
  mask_integrations_start: None
  spectro_sampler: joint_nuts
  spectro_jitter_prior: log_uniform
  lowres_num_warmup: 1000
  lowres_num_samples: 1000
  highres_num_warmup: 1000
  highres_num_samples: 1000
  whitelight_num_warmup: 1000
  whitelight_num_samples: 1000
outlier_clip:
  whitelight_sigma: 5
  spectroscopic_sigma: 5
host_device: gpu
